### ISSUE TITLE
CSRF Example

### ISSUE THREAD

**Issue by shujaatak** [salvo-rs/salvo#161]
It would be so helpful to have an example of CSRF in the list please.

**Comment by chrislearn** [comment]
https://github.com/salvo-rs/salvo/tree/main/examples/csrf-cookie-store
https://github.com/salvo-rs/salvo/tree/main/examples/csrf-session-store

**Comment by shujaatak** [comment]
Love the Salvo and its fast support!

**Comment by shujaatak** [comment]
It seems quite different than poem [csrf example](https://github.com/poem-web/poem/blob/master/examples/poem/csrf/src/main.rs) but worth it.

**Comment by chrislearn** [comment]
I have checked poem's csrf, it use https://crates.io/crates/csrf,  this crate's last commit is about 2 years ago, this crate may stop maintenance.

Poem does not need setup key, because it use default key value.
https://github.com/poem-web/poem/blob/master/poem/src/middleware/csrf.rs#L91

The new csrf middleware in salvo require you setup key for many ciphers.
There many new features:
1. You can use different kind of store to store csrf's data, like CookieStore, SessionStore.  If you use SessionStore, You need add SessionHandler as middleware before csrf.
2. You can choose different ciphers.
3. You can choose custom CSRF token length.

Examples has updated, they shows how to use different ciphers.

**Comment by shujaatak** [comment]
Simply wonderful 👍
