### ISSUE TITLE
About  "Too many open files"

### ISSUE THREAD

**Issue by Zheby** [salvo-rs/salvo#693]
**Describe the bug**
when i appears when a program is stress-tested "Too many open files"

**To Reproduce**
![截图 2024-02-26 02-47-57](https://github.com/salvo-rs/salvo/assets/113359077/b23cbf4f-4d71-4d0b-98a8-03fcd9408b72)
this is a easy code,Moreover, it can be accessed normally in the browser
![截图 2024-02-26 02-49-13](https://github.com/salvo-rs/salvo/assets/113359077/e778e40e-b29d-4245-9273-e2a3ab81450d)
Here's my jmeter config
![截图 2024-02-26 02-50-40](https://github.com/salvo-rs/salvo/assets/113359077/00c7edac-c244-4fbd-8adf-76d447ff2f42)
![截图 2024-02-26 02-50-33](https://github.com/salvo-rs/salvo/assets/113359077/e7116cfd-9d6d-4cad-a6ea-5a7f95fb327e)
But when I started, less than a minute later, an error came from the console
![image](https://github.com/salvo-rs/salvo/assets/113359077/5a41e8b7-2833-469e-8b29-e4d73e4975a1)

**Expected behavior**
I'd like it to be printed, but that's not what I'm expecting at the moment

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser chrome
 - Version 121.0.6167.184
 - create version 0.66.0
 - rust version 1.76.0
 - jmeter version 5.6.3

**Comment by hubertshelley** [comment]
应该是打开文件数的限制
可以参考设置：https://linux.cn/article-11077-1.html

**Comment by rxdiscovery** [comment]
If you see the "Too many files open" error message in Linux, your process has hit the upper limit of files it's allowed to open, usually 1,024. You can temporarily increase the limit to, for example, 2,048 files, with the command "ulimit -n 2048". Increase the limit permanently by editing systemd configuration files.

do a "sudo ulimit -n 99999" before starting the application, normally you won't have this problem anymore. (then you need to modify the system configuration file so that the configuration remains persistent after a Linux reboot.)
